workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.yourname.messageapp"  # ⚠️ Sửa cho đúng với app bạn

    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Get packages
        script: |
          flutter pub get

      - name: Build iOS release (.ipa)
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - ton13082008@gmail.com
        notify:
          success: true
          failure: true
