// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgo6KzsPZDbqB_UdSW5Vf-AtS8oyDiMIo',
    appId: '1:964895335690:web:d5081e436820ddbfb986f3',
    messagingSenderId: '964895335690',
    projectId: 'app-mess-217e4',
    authDomain: 'app-mess-217e4.firebaseapp.com',
    storageBucket: 'app-mess-217e4.firebasestorage.app',
    measurementId: 'G-953BRSEW39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYeS_VMkW_24d1DyPOVPgpaRY_GqBgiyQ',
    appId: '1:964895335690:android:5a7cb4d5aa2453a2b986f3',
    messagingSenderId: '964895335690',
    projectId: 'app-mess-217e4',
    storageBucket: 'app-mess-217e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMApGKmtKyFTulrnHo2wabPgilRHlysI',
    appId: '1:964895335690:ios:9a4b0d31c965f0cbb986f3',
    messagingSenderId: '964895335690',
    projectId: 'app-mess-217e4',
    storageBucket: 'app-mess-217e4.firebasestorage.app',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGMApGKmtKyFTulrnHo2wabPgilRHlysI',
    appId: '1:964895335690:ios:9a4b0d31c965f0cbb986f3',
    messagingSenderId: '964895335690',
    projectId: 'app-mess-217e4',
    storageBucket: 'app-mess-217e4.firebasestorage.app',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgo6KzsPZDbqB_UdSW5Vf-AtS8oyDiMIo',
    appId: '1:964895335690:web:3080f6b019c071bcb986f3',
    messagingSenderId: '964895335690',
    projectId: 'app-mess-217e4',
    authDomain: 'app-mess-217e4.firebaseapp.com',
    storageBucket: 'app-mess-217e4.firebasestorage.app',
    measurementId: 'G-7SPLDBKTL9',
  );
}
